- name: Manage EC2 by tags
  hosts: all
  become: true
  gather_facts: yes
  vars:
    is_managed: >-
      {{
        (hostvars[inventory_hostname].tags.Managed | default('false') | string | lower)
        in ['true','1','yes']
      }}
  pre_tasks:
    - name: Skip host if not managed
      ansible.builtin.meta: end_host
      when: not is_managed
  roles:
    - common
    - service
    - restart
